// src/main/webapp/app/entities/job-history/job-history-update.tsx
import React, { useState, useEffect } from 'react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { Button, Row, Col, FormText, UncontrolledTooltip } from 'reactstrap';
import { isNumber, Translate, translate, ValidatedField, ValidatedForm } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { convertDateTimeFromServer, convertDateTimeToServer, displayDefaultDateTime } from 'app/shared/util/date-utils';
import { mapIdList } from 'app/shared/util/entity-utils';
import { useAppDispatch, useAppSelector } from 'app/config/store';

import { IJob } from 'app/shared/model/job.model';
import { getEntities as getJobs } from 'app/entities/job/job.reducer';
import { IDepartment } from 'app/shared/model/department.model';
import { getEntities as getDepartments } from 'app/entities/department/department.reducer';
import { IEmployee } from 'app/shared/model/employee.model';
import { getEntities as getEmployees } from 'app/entities/employee/employee.reducer';
import { IJobHistory } from 'app/shared/model/job-history.model';
import { Language } from 'app/shared/model/enumerations/language.model';
import { getEntity, updateEntity, createEntity, reset } from './job-history.reducer';

export const JobHistoryUpdate = () => {
  const dispatch = useAppDispatch();

  const navigate = useNavigate();

  const { id } = useParams<'id'>();
  const isNew = id === undefined;

  const jobs = useAppSelector(state => state.job.entities);
  const departments = useAppSelector(state => state.department.entities);
  const employees = useAppSelector(state => state.employee.entities);
  const jobHistoryEntity = useAppSelector(state => state.jobHistory.entity);
  const loading = useAppSelector(state => state.jobHistory.loading);
  const updating = useAppSelector(state => state.jobHistory.updating);
  const updateSuccess = useAppSelector(state => state.jobHistory.updateSuccess);
  const languageValues = Object.keys(Language);

  const handleClose = () => {
    navigate('/job-history');
  };

  useEffect(() => {
    if (!isNew) {
      dispatch(getEntity(id));
    }

    dispatch(getJobs({}));
    dispatch(getDepartments({}));
    dispatch(getEmployees({}));
  }, []);

  useEffect(() => {
    if (updateSuccess) {
      handleClose();
    }
  }, [updateSuccess]);

  // eslint-disable-next-line complexity
  const saveEntity = values => {
    if (values.id !== undefined && typeof values.id !== 'number') {
      values.id = Number(values.id);
    }
    values.startDate = convertDateTimeToServer(values.startDate);
    values.endDate = convertDateTimeToServer(values.endDate);

    const entity = {
      ...jobHistoryEntity,
      ...values,
      job: jobs.find(it => it.id.toString() === values.job?.toString()),
      department: departments.find(it => it.id.toString() === values.department?.toString()),
      employee: employees.find(it => it.id.toString() === values.employee?.toString()),
    };

    if (isNew) {
      dispatch(createEntity(entity));
    } else {
      dispatch(updateEntity(entity));
    }
  };

  const defaultValues = () =>
    isNew
      ? {
          startDate: displayDefaultDateTime(),
          endDate: displayDefaultDateTime(),
        }
      : {
          language: 'FRENCH',
          ...jobHistoryEntity,
          startDate: convertDateTimeFromServer(jobHistoryEntity.startDate),
          endDate: convertDateTimeFromServer(jobHistoryEntity.endDate),
          job: jobHistoryEntity?.job?.id,
          department: jobHistoryEntity?.department?.id,
          employee: jobHistoryEntity?.employee?.id,
        };

  return (
    <div>
      <Row className="justify-content-center">
        <Col md="8">
          <h2 id="jobApp.jobHistory.home.createOrEditLabel" data-cy="JobHistoryCreateUpdateHeading">
            <Translate contentKey="jobApp.jobHistory.home.createOrEditLabel">Create or edit a JobHistory</Translate>
          </h2>
        </Col>
      </Row>
      <Row className="justify-content-center">
        <Col md="8">
          {loading ? (
            <p>Loading...</p>
          ) : (
            <ValidatedForm defaultValues={defaultValues()} onSubmit={saveEntity}>
              {!isNew ? (
                <ValidatedField
                  name="id"
                  required
                  readOnly
                  id="job-history-id"
                  label={translate('global.field.id')}
                  validate={{ required: true }}
                />
              ) : null}
              <ValidatedField
                label={translate('jobApp.jobHistory.startDate')}
                id="job-history-startDate"
                name="startDate"
                data-cy="startDate"
                type="datetime-local"
                placeholder="YYYY-MM-DD HH:mm"
              />
              <ValidatedField
                label={translate('jobApp.jobHistory.endDate')}
                id="job-history-endDate"
                name="endDate"
                data-cy="endDate"
                type="datetime-local"
                placeholder="YYYY-MM-DD HH:mm"
              />
              <ValidatedField
                label={translate('jobApp.jobHistory.language')}
                id="job-history-language"
                name="language"
                data-cy="language"
                type="select"
              >
                {languageValues.map(language => (
                  <option value={language} key={language}>
                    {translate('jobApp.Language.' + language)}
                  </option>
                ))}
              </ValidatedField>
              <UncontrolledTooltip target="languageLabel">
                <Translate contentKey="jobApp.jobHistory.help.language" />
              </UncontrolledTooltip>
              <ValidatedField id="job-history-job" name="job" data-cy="job" label={translate('jobApp.jobHistory.job')} type="select">
                <option value="" key="0" />
                {jobs
                  ? jobs.map(otherEntity => (
                      <option value={otherEntity.id} key={otherEntity.id}>
                        {otherEntity.id}
                      </option>
                    ))
                  : null}
              </ValidatedField>
              <ValidatedField
                id="job-history-department"
                name="department"
                data-cy="department"
                label={translate('jobApp.jobHistory.department')}
                type="select"
              >
                <option value="" key="0" />
                {departments
                  ? departments.map(otherEntity => (
                      <option value={otherEntity.id} key={otherEntity.id}>
                        {otherEntity.id}
                      </option>
                    ))
                  : null}
              </ValidatedField>
              <ValidatedField
                id="job-history-employee"
                name="employee"
                data-cy="employee"
                label={translate('jobApp.jobHistory.employee')}
                type="select"
              >
                <option value="" key="0" />
                {employees
                  ? employees.map(otherEntity => (
                      <option value={otherEntity.id} key={otherEntity.id}>
                        {otherEntity.id}
                      </option>
                    ))
                  : null}
              </ValidatedField>
              <Button tag={Link} id="cancel-save" data-cy="entityCreateCancelButton" to="/job-history" replace color="info">
                <FontAwesomeIcon icon="arrow-left" />
                &nbsp;
                <span className="d-none d-md-inline">
                  <Translate contentKey="entity.action.back">Back</Translate>
                </span>
              </Button>
              &nbsp;
              <Button color="primary" id="save-entity" data-cy="entityCreateSaveButton" type="submit" disabled={updating}>
                <FontAwesomeIcon icon="save" />
                &nbsp;
                <Translate contentKey="entity.action.save">Save</Translate>
              </Button>
            </ValidatedForm>
          )}
        </Col>
      </Row>
    </div>
  );
};

export default JobHistoryUpdate;

// src/main/webapp/app/entities/job-history/update/job-history-update.component.ts
import { Component, inject, OnInit } from '@angular/core';
import { HttpResponse } from '@angular/common/http';
import { ActivatedRoute } from '@angular/router';
import { Observable } from 'rxjs';
import { finalize, map } from 'rxjs/operators';

import SharedModule from 'app/shared/shared.module';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';

import { IJob } from 'app/entities/job/job.model';
import { JobService } from 'app/entities/job/service/job.service';
import { IDepartment } from 'app/entities/department/department.model';
import { DepartmentService } from 'app/entities/department/service/department.service';
import { IEmployee } from 'app/entities/employee/employee.model';
import { EmployeeService } from 'app/entities/employee/service/employee.service';
import { Language } from 'app/entities/enumerations/language.model';
import { JobHistoryService } from '../service/job-history.service';
import { IJobHistory } from '../job-history.model';
import { JobHistoryFormService, JobHistoryFormGroup } from './job-history-form.service';

@Component({
  standalone: true,
  selector: 'jhi-job-history-update',
  templateUrl: './job-history-update.component.html',
  imports: [SharedModule, FormsModule, ReactiveFormsModule],
})
export class JobHistoryUpdateComponent implements OnInit {
  isSaving = false;
  jobHistory: IJobHistory | null = null;
  languageValues = Object.keys(Language);

  jobsCollection: IJob[] = [];
  departmentsCollection: IDepartment[] = [];
  employeesCollection: IEmployee[] = [];

  protected jobHistoryService = inject(JobHistoryService);
  protected jobHistoryFormService = inject(JobHistoryFormService);
  protected jobService = inject(JobService);
  protected departmentService = inject(DepartmentService);
  protected employeeService = inject(EmployeeService);
  protected activatedRoute = inject(ActivatedRoute);

  // eslint-disable-next-line @typescript-eslint/member-ordering
  editForm: JobHistoryFormGroup = this.jobHistoryFormService.createJobHistoryFormGroup();

  compareJob = (o1: IJob | null, o2: IJob | null): boolean => this.jobService.compareJob(o1, o2);

  compareDepartment = (o1: IDepartment | null, o2: IDepartment | null): boolean => this.departmentService.compareDepartment(o1, o2);

  compareEmployee = (o1: IEmployee | null, o2: IEmployee | null): boolean => this.employeeService.compareEmployee(o1, o2);

  ngOnInit(): void {
    this.activatedRoute.data.subscribe(({ jobHistory }) => {
      this.jobHistory = jobHistory;
      if (jobHistory) {
        this.updateForm(jobHistory);
      }

      this.loadRelationshipsOptions();
    });
  }

  previousState(): void {
    window.history.back();
  }

  save(): void {
    this.isSaving = true;
    const jobHistory = this.jobHistoryFormService.getJobHistory(this.editForm);
    if (jobHistory.id !== null) {
      this.subscribeToSaveResponse(this.jobHistoryService.update(jobHistory));
    } else {
      this.subscribeToSaveResponse(this.jobHistoryService.create(jobHistory));
    }
  }

  protected subscribeToSaveResponse(result: Observable<HttpResponse<IJobHistory>>): void {
    result.pipe(finalize(() => this.onSaveFinalize())).subscribe({
      next: () => this.onSaveSuccess(),
      error: () => this.onSaveError(),
    });
  }

  protected onSaveSuccess(): void {
    this.previousState();
  }

  protected onSaveError(): void {
    // Api for inheritance.
  }

  protected onSaveFinalize(): void {
    this.isSaving = false;
  }

  protected updateForm(jobHistory: IJobHistory): void {
    this.jobHistory = jobHistory;
    this.jobHistoryFormService.resetForm(this.editForm, jobHistory);

    this.jobsCollection = this.jobService.addJobToCollectionIfMissing<IJob>(this.jobsCollection, jobHistory.job);
    this.departmentsCollection = this.departmentService.addDepartmentToCollectionIfMissing<IDepartment>(
      this.departmentsCollection,
      jobHistory.department,
    );
    this.employeesCollection = this.employeeService.addEmployeeToCollectionIfMissing<IEmployee>(
      this.employeesCollection,
      jobHistory.employee,
    );
  }

  protected loadRelationshipsOptions(): void {
    this.jobService
      .query({ 'jobHistoryId.specified': 'false' })
      .pipe(map((res: HttpResponse<IJob[]>) => res.body ?? []))
      .pipe(map((jobs: IJob[]) => this.jobService.addJobToCollectionIfMissing<IJob>(jobs, this.jobHistory?.job)))
      .subscribe((jobs: IJob[]) => (this.jobsCollection = jobs));

    this.departmentService
      .query({ 'jobHistoryId.specified': 'false' })
      .pipe(map((res: HttpResponse<IDepartment[]>) => res.body ?? []))
      .pipe(
        map((departments: IDepartment[]) =>
          this.departmentService.addDepartmentToCollectionIfMissing<IDepartment>(departments, this.jobHistory?.department),
        ),
      )
      .subscribe((departments: IDepartment[]) => (this.departmentsCollection = departments));

    this.employeeService
      .query({ 'jobHistoryId.specified': 'false' })
      .pipe(map((res: HttpResponse<IEmployee[]>) => res.body ?? []))
      .pipe(
        map((employees: IEmployee[]) =>
          this.employeeService.addEmployeeToCollectionIfMissing<IEmployee>(employees, this.jobHistory?.employee),
        ),
      )
      .subscribe((employees: IEmployee[]) => (this.employeesCollection = employees));
  }
}

<div class="d-flex justify-content-center">
  <div class="col-8">
    <form name="editForm" role="form" novalidate (ngSubmit)="save()" [formGroup]="editForm">
      <h2 id="jhi-job-history-heading" data-cy="JobHistoryCreateUpdateHeading" jhiTranslate="jobApp.jobHistory.home.createOrEditLabel">
        Create or edit a Job History
      </h2>

      <div>
        <jhi-alert-error></jhi-alert-error>

        @if (editForm.controls.id.value !== null) {
          <div class="mb-3">
            <label class="form-label" for="field_id" jhiTranslate="jobApp.jobHistory.id">ID</label>
            <input type="number" class="form-control" name="id" id="field_id" data-cy="id" formControlName="id" [readonly]="true" />
          </div>
        }

        <div class="mb-3">
          <label class="form-label" for="field_startDate" jhiTranslate="jobApp.jobHistory.startDate">Start Date</label>
          <div class="d-flex">
            <input
              id="field_startDate"
              data-cy="startDate"
              type="datetime-local"
              class="form-control"
              name="startDate"
              formControlName="startDate"
              placeholder="YYYY-MM-DD HH:mm"
            />
          </div>
        </div>

        <div class="mb-3">
          <label class="form-label" for="field_endDate" jhiTranslate="jobApp.jobHistory.endDate">End Date</label>
          <div class="d-flex">
            <input
              id="field_endDate"
              data-cy="endDate"
              type="datetime-local"
              class="form-control"
              name="endDate"
              formControlName="endDate"
              placeholder="YYYY-MM-DD HH:mm"
            />
          </div>
        </div>

        <div class="mb-3">
          <label
            class="form-label"
            for="field_language"
            [ngbTooltip]="'jobApp.jobHistory.help.language' | translate"
            jhiTranslate="jobApp.jobHistory.language"
            >Language</label
          >
          <select class="form-control" name="language" formControlName="language" id="field_language" data-cy="language">
            <option [ngValue]="null">{{ 'jobApp.Language.null' | translate }}</option>
            @for (language of languageValues; track $index) {
              <option [value]="language">{{ 'jobApp.Language.' + language | translate }}</option>
            }
          </select>
        </div>

        <div class="mb-3">
          <label class="form-label" for="field_job" jhiTranslate="jobApp.jobHistory.job">Job</label>
          <select class="form-control" id="field_job" data-cy="job" name="job" formControlName="job" [compareWith]="compareJob">
            <option [ngValue]="null"></option>
            @for (jobOption of jobsCollection; track $index) {
              <option [ngValue]="jobOption">{{ jobOption.id }}</option>
            }
          </select>
        </div>

        <div class="mb-3">
          <label class="form-label" for="field_department" jhiTranslate="jobApp.jobHistory.department">Department</label>
          <select
            class="form-control"
            id="field_department"
            data-cy="department"
            name="department"
            formControlName="department"
            [compareWith]="compareDepartment"
          >
            <option [ngValue]="null"></option>
            @for (departmentOption of departmentsCollection; track $index) {
              <option [ngValue]="departmentOption">{{ departmentOption.id }}</option>
            }
          </select>
        </div>

        <div class="mb-3">
          <label class="form-label" for="field_employee" jhiTranslate="jobApp.jobHistory.employee">Employee</label>
          <select
            class="form-control"
            id="field_employee"
            data-cy="employee"
            name="employee"
            formControlName="employee"
            [compareWith]="compareEmployee"
          >
            <option [ngValue]="null"></option>
            @for (employeeOption of employeesCollection; track $index) {
              <option [ngValue]="employeeOption">{{ employeeOption.id }}</option>
            }
          </select>
        </div>
      </div>

      <div>
        <button type="button" id="cancel-save" data-cy="entityCreateCancelButton" class="btn btn-secondary" (click)="previousState()">
          <fa-icon icon="ban"></fa-icon>&nbsp;<span jhiTranslate="entity.action.cancel">Cancel</span>
        </button>

        <button
          type="submit"
          id="save-entity"
          data-cy="entityCreateSaveButton"
          [disabled]="editForm.invalid || isSaving"
          class="btn btn-primary"
        >
          <fa-icon icon="save"></fa-icon>&nbsp;<span jhiTranslate="entity.action.save">Save</span>
        </button>
      </div>
    </form>
  </div>
</div>
